
export const site = {
  name: "Jennifer Lago",
  firstName: "Jennifer",
  profession: "Psicóloga · Psicanalista",
  registration: "CRP 01/26397",
  city: "Brasília",
  neighborhood: "Asa Sul",
  address: "SHN, Quadra 1, Bloco D, Sala 1107, Conjunto A, 11º andar, Edifício Fusion Work e Live, Asa Sul, Brasília — DF, 70701-040",
  mapUrl: "https://www.google.com/maps/search/?api=1&query=-15.7898359,-47.8852539",
  profileUrl: "https://www.doctoralia.com.br/jennifer-lago/psicologo-psicanalista/brasilia",
  reviewUrl: "https://www.doctoralia.com.br/jennifer-lago/psicologo-psicanalista/brasilia#profile-reviews",
  bookingLabel: "Agendar consulta",
  appointmentDuration: "Atendimento individual",
  price: "R$ 180",
  rating: "5,0",
  reviewCount: 19,
  portrait: "/assets/jennifer-lago-retrato.jpg",
  office: "/assets/consultorio-jennifer-lago.jpg",
  reading: "/assets/jennifer-lago-freud.jpg",
  education: [
    "Graduação em Psicologia pelo UniCEUB (2022)",
    "Formação básica em Psicanálise pelo Corpo Freudiano de Brasília (2024)",
    "Mestrado em Psicologia pela Arden University (concluído)",
    "Autora de livro e capítulo sobre transtornos alimentares e tratamentos psicológicos com suporte empírico",
  ],
  specialties: ["Psicanálise", "Ansiedade", "Transtornos alimentares", "Relacionamentos", "Depressão"],
  concerns: [
    { title: "Ansiedade e estresse", text: "Quando a inquietação ocupa mais espaço do que você gostaria." },
    { title: "Relações e conflitos", text: "Quando certos encontros parecem repetir os mesmos impasses." },
    { title: "Alimentação e corpo", text: "Quando a relação com a comida e com a própria imagem pesa no dia a dia." },
    { title: "Humor e depressão", text: "Quando os dias parecem pesados e é difícil nomear o que acontece." },
    { title: "Autoestima", text: "Quando a voz interna é dura demais e faltam palavras para si mesma(o)." },
    { title: "Trabalho e esgotamento", text: "Quando o cansaço, a insônia e a cobrança tomam conta da rotina." },
  ],
  services: [
    { name: "Psicoterapia presencial", description: "Atendimento psicológico individual para adultos no consultório em Brasília.", mode: "Presencial · Brasília", duration: "Atendimento individual", price: "R$ 180" },
    { name: "Psicoterapia online", description: "Teleconsulta para quem mora em Brasília, em outra cidade ou no exterior.", mode: "Online", duration: "Atendimento individual", price: "R$ 180" },
    { name: "Psicanálise e análise pessoal", description: "Processo de escuta psicanalítica, presencial ou online, no seu tempo.", mode: "Presencial ou online", duration: "Atendimento individual", price: "R$ 180" },
  ],
  reviews: [
    { quote: "Eu me senti muito bem acolhido(a) durante a terapia. As conversas aconteceram em um ambiente calmo e de confiança, e houve uma escuta atenta.", author: "Hendrik" },
    { quote: "A Dra. Jennifer é uma excelente profissional! Muito atenciosa e uma ótima ouvinte. Suas observações são sempre muito pertinentes e trazem reflexões muito interessantes e necessárias.", author: "Isabela Frances" },
    { quote: "Profissional incrível, atenciosa e muito competente. Sempre me acolhe com empatia e me ajuda a ver as situações de forma mais leve.", author: "Vanessa Alves" },
    { quote: "Eu realmente me sinto muito à vontade, eu amei o trabalho dela e ela me ajudou a entender bastante coisa sobre minha vida.", author: "SG" },
  ],
} as const;
